server:
  port: 9000
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8660/eureka/
#服务的名称
spring:
  application:
    name: api-gateway
zuul:
  routes:
  #服务名路由称映射
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
    #添加ignored-patterns只能通过/apigateway/** 去访问
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题
  sensitiveHeaders:
  #忽略整个服务，对外提供接口
  #ignored-services: product-service

